name: Retag image

on:
  watch:
    types: [started]
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: docker
      uses: docker/build-push-action@v1
      run: docker ps
